In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [4]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [5]:
arr = np.array([1, 2, 3, 4])
arr[1]

2

In [6]:
arr[2::1]


array([3, 4])

In [7]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [8]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [9]:
#i - integer
#b - boolean
#u - unsigned integer
#f - float
#c - complex float 
#S - string
#U - unicode string

In [10]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [11]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr.shape

(2, 4)

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [46]:
arr1 = np.array([[1, 2, 3],[7,8,9]])
arr2 = np.array([[4, 5, 6],[10,11,12]])
arr = np.concatenate((arr1, arr2),axis=1)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [17]:
arr1 = np.array([[1, 2, 3],[7,8,9]])
arr2 = np.array([[4, 5, 6],[10,11,12]])
arr = np.concatenate((arr1, arr2),axis=1)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
x

(array([0, 2, 4, 6], dtype=int64),)

In [20]:
arr = np.array([3, 2, 0, 1])
np.sort(arr)

array([0, 1, 2, 3])

In [21]:
arr = np.array([41, 42, 43, 44])
x = arr[[True, True, True, False]]
x

array([41, 42, 43])

In [22]:
a = np.array([41, 42, 43, 44])
a[a>42]

array([43, 44])

In [23]:
from numpy import random
x = random.randint(0,100)
x

86

In [24]:
x = random.rand()
x

0.9044689278209538

In [25]:
#np.sort(arr)[::-1]
x=random.randint(100, size=(5))
x

array([ 6, 56,  2,  9,  5])

In [26]:
x = random.randint(100, size=(3, 5))
x

array([[53, 53, 58, 12, 24],
       [13, 32, 64, 92, 29],
       [95, 61, 98, 86, 86]])

In [27]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
x

array([[5, 5, 7, 3, 7],
       [5, 3, 3, 3, 5],
       [9, 5, 5, 7, 5]])

In [28]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0],
                              size=(10))
x

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 5])

In [29]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []
for i, j in zip(x, y):
  z.append(i + j)
z

[5, 7, 9, 11]

In [30]:
list(zip(x, y))

[(1, 4), (2, 5), (3, 6), (4, 7)]

In [31]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)
z

array([ 5,  7,  9, 11])

In [32]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.add(arr1, arr2)
newarr

array([30, 32, 34, 36, 38, 40])

In [33]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.subtract(arr1, arr2)
newarr

array([-10,  -1,   8,  17,  26,  35])

In [34]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.multiply(arr1, arr2)
newarr

array([ 200,  420,  660,  920, 1200, 1500])

In [35]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
newarr = np.divide(arr1, arr2)
newarr

array([ 3.33333333,  4.        ,  3.        ,  5.        , 25.        ,
        1.81818182])

In [36]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])
newarr = np.power(arr1, arr2)
newarr

array([      1000,    3200000,  729000000, -520093696,       2500,
                0])

In [37]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.mod(arr1, arr2)
newarr

array([ 1,  6,  3,  0,  0, 27])

In [38]:
arr1 = np.array([10, 20, 30, 40, 50, 60],dtype=np.32)
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.remainder(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]


In [39]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.divmod(arr1, arr2)
newarr

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))

In [40]:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)
newarr

array([1, 2, 1, 2, 3, 4])

In [41]:
arr = np.fix([-3.1666, 3.6667])
arr

array([-3.,  3.])

In [42]:
arr = np.around(3.1666, 2)
arr

3.17

In [43]:
arr = np.floor([-3.1666, 3.6667])
arr

array([-4.,  3.])

In [44]:
arr = np.ceil([-3.1666, 3.6667])
arr

array([-3.,  4.])

In [45]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2], axis=0)
newarr

array([2, 4, 6])